<?php
/**
 * Custom Ability Assets Handler
 *
 * Handles enqueuing of JavaScript and CSS for Custom Abilities admin UI.
 *
 * @package AcrossAI_Abilities_Manager
 * @subpackage Admin\Partials
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * AcrossAI_Custom_Ability_Assets class
 *
 * Singleton: Manages asset enqueue for Custom Abilities admin interface.
 *
 * @since 1.0.0
 */
class AcrossAI_Custom_Ability_Assets {

	/**
	 * Singleton instance
	 *
	 * @since 1.0.0
	 * @var AcrossAI_Custom_Ability_Assets
	 */
	protected static $_instance = null;

	/**
	 * Asset manifest data
	 *
	 * @since 1.0.0
	 * @var array
	 */
	private $asset_file = array();

	/**
	 * Get singleton instance
	 *
	 * @since 1.0.0
	 * @return AcrossAI_Custom_Ability_Assets
	 */
	public static function instance() {
		if ( null === self::$_instance ) {
			self::$_instance = new self();
		}
		return self::$_instance;
	}

	/**
	 * Constructor
	 *
	 * Loads asset manifest for dynamic versioning and dependencies.
	 *
	 * @since 1.0.0
	 */
	private function __construct() {
		// Load asset manifest (generated by @wordpress/scripts build)
		$asset_file = ACROSSAI_ABILITIES_MANAGER_PLUGIN_PATH . 'build/js/custom-abilities.asset.php';
		if ( file_exists( $asset_file ) ) {
			$this->asset_file = include $asset_file;
		} else {
			// Fallback if asset file not found (during development)
			$this->asset_file = array(
				'dependencies' => array( 'wp-react', 'wp-react-dom', 'wp-dataviews', 'wp-i18n' ),
				'version'      => filemtime( ACROSSAI_ABILITIES_MANAGER_PLUGIN_PATH . 'src/js/admin/custom-abilities/index.js' ),
			);
		}
	}

	/**
	 * Enqueue JavaScript
	 *
	 * Hooked at admin_enqueue_scripts priority 10.
	 * Only enqueues on acrossai-custom-abilities page.
	 *
	 * @since 1.0.0
	 * @param string $hook_suffix Current admin page hook suffix.
	 * @return void
	 */
	public function enqueue_scripts( $hook_suffix = '' ) {
		// Get current hook suffix if not provided
		if ( empty( $hook_suffix ) ) {
			global $hook_suffix;
		}

		// Only enqueue on Custom Abilities page
		if ( 'acrossai-abilities-manager_page_acrossai-custom-abilities' !== $hook_suffix ) {
			return;
		}

		$script_path  = 'build/js/custom-abilities.js';
		$script_url   = ACROSSAI_ABILITIES_MANAGER_PLUGIN_URL . $script_path;
		$script_asset = $this->asset_file;

		wp_enqueue_script(
			'acrossai-abilities-custom',
			$script_url,
			isset( $script_asset['dependencies'] ) ? $script_asset['dependencies'] : array(),
			isset( $script_asset['version'] ) ? $script_asset['version'] : ACROSSAI_ABILITIES_MANAGER_VERSION,
			true
		);

		// Set text domain for i18n
		wp_set_script_translations(
			'acrossai-abilities-custom',
			'acrossai-abilities-manager',
			ACROSSAI_ABILITIES_MANAGER_PLUGIN_PATH . 'languages'
		);
	}

	/**
	 * Enqueue Stylesheets
	 *
	 * Hooked at admin_enqueue_scripts priority 10.
	 * Only enqueues on acrossai-custom-abilities page.
	 *
	 * @since 1.0.0
	 * @param string $hook_suffix Current admin page hook suffix.
	 * @return void
	 */
	public function enqueue_styles( $hook_suffix = '' ) {
		// Get current hook suffix if not provided
		if ( empty( $hook_suffix ) ) {
			global $hook_suffix;
		}

		// Only enqueue on Custom Abilities page
		if ( 'acrossai-abilities-manager_page_acrossai-custom-abilities' !== $hook_suffix ) {
			return;
		}

		$style_path = 'build/css/custom-abilities.css';
		$style_url  = ACROSSAI_ABILITIES_MANAGER_PLUGIN_URL . $style_path;

		wp_enqueue_style(
			'acrossai-abilities-custom',
			$style_url,
			array( 'wp-components', 'wp-dataviews' ),
			ACROSSAI_ABILITIES_MANAGER_VERSION
		);
	}
}
